### ISSUE TITLE
/dev/null regression?

### ISSUE THREAD

**Issue by Ekatwikz** [membersincewayback/gen#17]
I see that [this commit](https://github.com/membersincewayback/gen/blob/ee6d8f6/gen#L146) is titled "more explicit errors", but isn't this less explicit than not suppressing stderr?
Why is it better to say that "touch failed" instead of letting `touch` say _why_ it failed, if it can fail for various reasons?

Again, I'd also argue that what's written to stderr for any command may even literally vary by system, why not present the information if we're going to exit anyway? Additionally, wouldn't you agree that informative errors are valuable? A user can for example look up what happened with `touch` (or some other source of errors) if it was neither our nor their fault, or get similarly support from a person who recognizes the default error message.
Additionally, suppressing just this (and `!$suppress`'?) error message is somewhat inconsistent, why do we hide only those, but we don't take care of the possibility of chmod (for example, among others) having an error?

I thought we'd gone over this already in [an earlier review](https://github.com/membersincewayback/gen/pull/15#discussion_r1034126293)?
I was starting a small feature PR and noticed this, are we officially regressing?

**Comment by membersincewayback** [comment]
Not sure how I closed this on accident. I think you're right. Does it look like the rest of the exit codes and `printf` statements will make sense if I just removed both redirects to /dev/null?
And yes, this does relate to the previous issue, you got it in my head and I was trying to make it clearer.

**Comment by membersincewayback** [comment]
After more testing, I think the current error reporting is consistent with common CLI tools. I may review it later if I find a notable exception.
