### ISSUE TITLE
Gen only works properly in the same folder that contains the templates

### ISSUE THREAD

**Issue by fearlessgeekmedia** [membersincewayback/gen#6]
Gen is only working properly if I'm working in the same folder which contains the template folder. Otherwise, you get something like 'touchhtml: command not found'.

**Comment by fearlessgeekmedia** [comment]
I think an easy solution could be to write the script where it places it in a common folder if it does not yet exists, such as ~/.config/templates/ and then have it read from ~/.config/templates.

**Comment by zpiatt** [comment]
I haven't gotten as far as an install script yet. I might just put the templates back in the main script for now until I figure that out. Thanks!

**Comment by zpiatt** [comment]
Temp fix for now. I integrated your JS template into the touchsh function as well. Let me know if that looks right to you. Closing this issue for now.

**Comment by fearlessgeekmedia** [comment]
Yes, it looks right to me. :)
